name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build dev image'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker-compose build ffmpeg-dev
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: docker-compose push ffmpeg-dev
