name: Build for win32

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        working-directory: ./scripts/win32
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: nasm pkg-config make
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Install
      run: ./vcvarsall ./install.sh
      shell: cmd
    - name: Build x64-windows-static
      run: ./vcvarsall ./build.sh x64-windows-static
      shell: cmd
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: build
    #     path: ../../build
